name: Install Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy-melange:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
      - name: Copy Files
        run: cp ${GITHUB_WORKSPACE}/giropops-senhas/melange.yaml ${GITHUB_WORKSPACE}/giropops-senhas/apko.yaml .
          
      - name: Generate the keys
        run: docker run --rm -v "${{ github.workspace }}":/work cgr.dev/chainguard/melange keygen
    
      - name: Create the package
        run: docker run --rm --privileged -v "${PWD}":/work -w /work cgr.dev/chainguard/melange build melange.yaml --arch host --signing-key melange.rsa
                        
      - name: Generate the .tar file
        run: docker run --rm -v "$PWD":/work -w /work cgr.dev/chainguard/apko build apko.yaml distroless-melange distroless-melange.tar -k melange.rsa.pub --arch host
    
      - name: Load the image
        run: docker load < distroless-melange.tar

      - name: Run the image
        run: docker run -p 5000:5000 distroless-melange:latest-amd64
