name: Install Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy-melange:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
      - name: Access Directory
        run: |
          ls -lha
          cd ${GITHUB_WORKSPACE}/giropops-senhas/
          ls -lha
            
      - name: Generate the keys
        run: |
          ls -lha
          docker run --rm -v "${PWD}/giropops-senhas/":/work cgr.dev/chainguard/melange keygen
    
      - name: Create the package
        run: docker run --rm --privileged -v "${PWD}/giropops-senhas/":/work -w /work cgr.dev/chainguard/melange build melange.yaml --arch host --signing-key melange.rsa
                        
      - name: Generate the .tar file
        run: docker run --rm -v "$PWD/giropops-senhas/":/work -w /work cgr.dev/chainguard/apko build apko.yaml distroless-melange distroless-melange.tar -k melange.rsa.pub --arch host
    
      - name: Load the image
        run: |
          docker load -i distroless-melange.tar
          ls -lha
      
      - name: Tag Docker image
        run: docker tag distroless-melange:latest ${{ secrets.DOCKER_USERNAME }}/distroless-melange:latest-amd64
  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
  
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
  
      - name: Push the Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/distroless-melange:latest-amd64
