name: Create apko package with Chainguard Melange

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  prepare-enviroment:
    runs-on: ubuntu-latest

    steps:
    - name: Using the multiarch/qemu-user-static image
      run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
