name: Create apko package with Chainguard Melange

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  prepare-enviroment:
    runs-on: ubuntu-latest

    steps:
    - name: Using the multiarch/qemu-user-static image
      run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      
    - name: Downloading the melange Image
      run: docker pull cgr.dev/chainguard/melange:latest

    - name: Check that you’re able to run melange with docker run
      run: docker run --rm cgr.dev/chainguard/melange version
